FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /App
COPY . ./
RUN dotnet restore
RUN apt update && apt install -y clang zlib1g-dev
RUN dotnet publish -p:PublishAot=true --arch x64 -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:8.0-jammy-chiseled
WORKDIR /App
COPY --from=build /App/out .
ENTRYPOINT ["dotnet", "ChiseledSorting.dll"]